### ISSUE TITLE
Not passing server-vars.yml

### ISSUE THREAD

**Issue by WolfieZero** [lpm0073/edx.ginkgo#2]
I've created a super basic `server-vars.yml` file

```yml
EDXAPP_PLATFORM_NAME: 'My Academy'
```

The script reads that there is such a file and moves it, but when look at my Open edX site, it still says "Your Platform Name Here".

The only real differences is I'm running on a t2.large with 50GB of EBS storage. But I've opened all the ports you've mentioned aside from SSH, which is closed to a IP range.

This occurs with both the install and update shell scripts.

(I appreciate this may not be an issue with your scripts pre-say but in case it is I thought I'll mention it).

Thanks.

**Comment by lpm0073** [comment]
please take a look at the /edx/bin/update around line 39 or so to ensure that you're referencing and including your server-vars.yml file. an example would look similar to the code that exists by default to include the my-passwords.yml file, such as:

if [[ -f /edx/app/edx_ansible/server-vars.yml ]]; then
    extra_args="-e@/edx/app/edx_ansible/server-vars.yml"
fi

**Comment by WolfieZero** [comment]
I'm a bit of a edx rookie so forgive me if I misunderstand anything. 

I've checked the `/edx/bin/update` file and, yup, those three lines are there.

Having a look though, the `/edx/app/edx_ansible/server-vars.yml` file is assigned as `root:root`. Should that not be assigned `edx-ansible:edx-ansible`?

**Comment by lpm0073** [comment]
at the risk of seeming OCD, please verify that you see TWO similarly patterned sets of code, one for server-vars.yml and the other for my-passwords.yml. please see attached screen shot example.

<img width="807" alt="screen shot 2018-02-14 at 16 08 30" src="https://user-images.githubusercontent.com/1178819/36230845-60e7cc94-11a1-11e8-9eb1-ed858906735f.png">

**Comment by WolfieZero** [comment]
Not a problem :)

![hyper 2018-02-14 22-12-04](https://user-images.githubusercontent.com/648761/36230968-31eeb7d0-11d4-11e8-926b-8a8c1d53b884.png)

Looks like I'm missing the password `if` statement. Why would that be?

**Comment by lpm0073** [comment]
it looks like you (aka someone) might have edited the original code fragment for my-passwords.yml as this is part of the script by default. at any rate, the update script will only work if you're adding extra_args for the values that are stored in my-passwords.yml (probably in /home/ubuntu/). you can refer to my screen shot above in order to reproduce.

**Comment by lpm0073** [comment]
to verify, you can look at the logs located in /edx/var/log/edxapp/lms  (PS you need to be sudo to get to this folder). you'll probably see some "Access Denied" errors from your previous attempts at updating

**Comment by WolfieZero** [comment]
Very strange. So nobody should be accessing the server as this is fresh as of ~5 hours ago, so nobody should be editing it...

I've checked the logs folder and it's empty, so what I'm going to do is manually add that block `/edx/bin/update` and see what happens. 

Forgive me if I'm mistaken (I'm trying my best to understand); the install script will only apply the `server-vars.yml` if it adds the `my-passwords.yml` to `extra_args`? But would that not overwrite the previous string meaning it ignores `server-vars.yml` anyway?

Sorry, it's late for me! :)

**Comment by lpm0073** [comment]
that's correct. more specifically, the file my-passwords.yml is created by the following line from "Native Open edX Ubuntu 16.04 64 bit Installation" 
# 3. (Optional) If this is a new installation, randomize the passwords:
wget https://raw.githubusercontent.com/edx/configuration/$OPENEDX_RELEASE/util/install/generate-passwords.sh -O - | bash

this script saves the resulting yml file in /home/ubuntu. the Update script assumes that this will exist. if the file contents are not added as extra args then the update script will have no means of authenticating the several dozen accounts across the app, mysql, mongo, celery, memcached, and so on.

**Comment by WolfieZero** [comment]
Cool, got it.

I'm running the update script now so I'll see what happens. I find it strange that the update file is different.

I'll let you know how I get on. I massively appreciate your time on this!

**Comment by WolfieZero** [comment]
Updated the `/edx/bin/update` file and ran your update script; didn't work.

I've decided to reinstall the whole thing again (fresh instance and all), doesn't read the server-vars.yml file still. II've not got step 3 commented out as you mentioned.

Not sure what's going wrong here really as nothing has changed but I did look at the `/edx/bin/update` file again after installing afresh, and the `my-passwords.yml` if statement isn't there again.

Might be a case of editing the .json files directly. :(

Thanks for the help, I dare say unless there's something you can do in your scripts it might be an issue with edX directly? But again, your help is much appreciated!

**Comment by lpm0073** [comment]
hi neal, that sheds light on things. my update script is not a replacement -- nor even an alternative for that matter -- to its namesake located in /edx/bin/. for what you're trying to do, you should follow this procedure: https://openedx.atlassian.net/wiki/spaces/OpenOPS/pages/60227913/Managing+OpenEdX+Tips+and+Tricks
